# orbit boundaries
ORBITS_MIN: 0.15
ORBITS_MAX: 0.79
ORBITS_LEFT: 0.62
ORBITS_RIGHT: 0.20

# table boundaries
TUIO_X_MIN: 0.09
TUIO_Y_MIN: 0.17
TUIO_X_MAX: 0.95
TUIO_Y_MAX: 0.8
ARM_X_DIST: 0.74
ARM_Y_DIST: 0.373
ARM_Y_MIN: -0.58
ARM_X_MIN: -0.32

STAGING_BUFFER_WIDTH: 0.15

GRASP_HEIGHT: 0.02
DROP_HEIGHT: 0.03
CRUISING_HEIGHT: 0.1
DEFAULT_BLOCK_SIZE: 0.135
