# orbit boundaries
ORBITS_MIN: 0.165
ORBITS_MAX: 0.79
ORBITS_LEFT: 0.62
ORBITS_RIGHT: 0.217

# table boundaries
TUIO_X_MIN: 0.09
TUIO_Y_MIN: 0.15
TUIO_X_MAX: 0.95
TUIO_Y_MAX: 0.95
ARM_X_DIST: 0.73
ARM_Y_DIST: 0.482
ARM_Y_MIN: -0.67
ARM_X_MIN: -0.328

STAGING_BUFFER_WIDTH: 0.14

GRASP_HEIGHT: 0.02
DROP_HEIGHT: 0.03
CRUISING_HEIGHT: 0.11
DEFAULT_BLOCK_SIZE: 0.11
