# orbit boundaries
ORBITS_MIN: -0.58
ORBITS_MAX: -0.17
ORBITS_LEFT: 0.25
ORBITS_RIGHT: 0.45

# table boundaries
TUIO_MIN_X: 0.09
TUIO_MIN_Y: 0.17
TUIO_MAX_X: 0.95
TUIO_MAX_Y: 0.8
ARM_X_DIST: 0.77
ARM_Y_DIST: 0.37
