# orbit boundaries
ORBITS_MIN: 0.165
ORBITS_MAX: 0.72
ORBITS_LEFT: 0.61
ORBITS_RIGHT: 0.16

# table boundaries
TUIO_X_MIN: 0.09
TUIO_Y_MIN: 0.17
TUIO_X_MAX: 0.95
TUIO_Y_MAX: 0.8
ARM_X_DIST: 0.77
ARM_Y_DIST: 0.37

GRASP_HEIGHT: 0.1
DROP_HEIGHT: 0.3
